### ISSUE TITLE
ref

### ISSUE THREAD

**Issue by Kochise** [frmdstryr/smd-search#2]
main.py#58 :

```python
         CACHE[viewer.ref] = viewer
```

viewer.enaml#151 :

```python
             '''% viewer.ref
```

Result:

```bash
>python main.py
Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "Python\lib\site-packages\tornado\web.py", line 1711, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "smd-search-master\main.py", line 58, in get
    CACHE[viewer.ref] = viewer
AttributeError: 'Viewer' object has no attribute 'ref'
500 GET / (::1) 2.92ms
```

**Comment by frmdstryr** [comment]
Sorry this repo is quite old. The ref attribute was removed. Change the uses of ref to id.

**Comment by Kochise** [comment]
Ok, will test that.

Btw, are you CodeLV ?

**Comment by Kochise** [comment]
Tried, but there are too many `/websocket/?ref=` around to have something functional.

**Comment by frmdstryr** [comment]
CodeLV is a website I made. Anyways, I pushed an update. Previously enaml-wb added an additional ref attribute to each node but it was later changed to just use the id attribute since that is easier.

**Comment by Kochise** [comment]
Ok

* for CodeLV, what is your tool/dashboard shown in https://www.codelv.com/blog/2021/7/new-site ?
* your update works well, yet upon trying, the search fields are case sensitive, which is a bit counter-intuitive

Regards.

PS : have a look at my `enaml` API documentation at https://github.com/Kochise/python-enaml_studio

**Comment by frmdstryr** [comment]
It is just a dashboard I made with enaml-web and golden layout (not open source).

**Comment by Kochise** [comment]
Done, thank.
